name: Publish tags to FlakeHub

on:
  push:
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

jobs:
  flakehub:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Push to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: unlisted
          rolling: true
